### PR TITLE
adding lps2x

### PR DESCRIPTION
**Pull request by siddacious**
new pressure sensor (family?)

### CODE REVIEW

**Comment by siddacious** [comment]
@ladyada looks like this is going to fail until the lib is added to the library manager:
https://github.com/arduino/Arduino/issues/9779

**Comment by ladyada** [comment]
yep we will wait until library manager is updated!

**Comment by ladyada** [comment]
please kick if in the library manager

**Comment by siddacious** [comment]
I released your fix for mpu6050 (thank you) but I'll be a while until the release percolates, right?

**Comment by ladyada** [comment]
yep check https://www.arduinolibraries.info/ to see latest arduino libraries that have been updated

**Pull request merged**
