### PR TITLE
Adding support for LSM6DS3TR-C

### PR DESCRIPTION
**Pull request by BlitzCityDIY**
Added support for LSM6DS3TR-C accelerometer.

Added `detectLSM6DS3TRC()` function
Added `detectLSM6DS3TRC()` function call in `getMagnetometer()` and `getAccelerometer()`
Added `#include <Adafruit_LSM6DS3TRC.h>` in header
Added `_lsm6ds3trc` private object pointer

Tested with `gyro_zerorate_simplecal.ino` and Jupyter Notebook. Thanks to Shawn Hymel's PR#16 as a reference.

### CODE REVIEW

**Comment by BlitzCityDIY** [comment]
hihi @ladyada - do i need to have it skip esp32 or is there a different issue happening?

**Comment by caternuson** [comment]
Do these need to be virtual? AFAICT, nothing is deriving from these classes.

https://github.com/adafruit/Adafruit_HTS221/blob/7e576492030c2219732b7c1011ee4a9ede3ae138/Adafruit_HTS221.h#L129
https://github.com/adafruit/Adafruit_MPU6050/blob/5836a1b0a4121779a69df24928c07fddfc8bd1f4/Adafruit_MPU6050.h#L290
https://github.com/adafruit/Adafruit_LPS2X/blob/6be7c2e5a0e18707c2085c11a1e89cb813c1a68c/Adafruit_LPS2X.h#L137

**Comment by brentru** [comment]
@caternuson  I don't think the MPU6050 or the HTS221 `_init` calls need to be `virtual` (nothing is derived), however the `LPS2X`'s might as it's used by [Adafruit_LPS22.cpp](https://github.com/adafruit/Adafruit_LPS2X/blob/6be7c2e5a0e18707c2085c11a1e89cb813c1a68c/Adafruit_LPS22.cpp) and [Adafruit_LPS25.cpp](https://github.com/adafruit/Adafruit_LPS2X/blob/6be7c2e5a0e18707c2085c11a1e89cb813c1a68c/Adafruit_LPS25.cpp)

**Comment by caternuson** [comment]
@brentru ooooooh yah. missed those. thanks! good catch.

**Comment by caternuson** [comment]
OK, so maybe these should stay as nominal base classes.

Looking elsewhere...it looks like the general idea for each of these `detectFoo` methods is to:
1. create an instance of `FooSensor`
2. get a pointer to a specific `Adafruit_Sensor` type sensor using `FooSensor::getSomeSensor()` and store locally
3. delete instance from (1), since we just needed it for `getSomeSensor()`

But it looks like the instance for (1) is still needed. It gets passed in when creating the subclass instance. Using `Adafruit_HTS221_Humidity` as an example. It gets created here:
https://github.com/adafruit/Adafruit_HTS221/blob/7e576492030c2219732b7c1011ee4a9ede3ae138/Adafruit_HTS221.cpp#L162
with `this` being the `Adafruit_HTS221` instance. It gets stored by the derived class's overriden ctor:
https://github.com/adafruit/Adafruit_HTS221/blob/7e576492030c2219732b7c1011ee4a9ede3ae138/Adafruit_HTS221.h#L69

So is it OK to then delete that original instance?
https://github.com/adafruit/Adafruit_SensorLab/blob/7deb410beb6e1de5d00ac94c7f366bbf9c135847/Adafruit_SensorLab.cpp#L342

**Comment by brentru** [comment]
@caternuson  I believe so.. I encountered this issue with WipperSnapper Arduino (similar sensor handling as sensorlab) with ESP32 (strict GCC checks on 2.0.4) as well and don't think I solved it well.

**Comment by BlitzCityDIY** [comment]
hi @caternuson when you have a chance can you help me with this? I'm not sure why the checks failed.

**Comment by ladyada** [comment]
you have to add the new library to
https://github.com/adafruit/Adafruit_SensorLab/blob/master/library.properties

**Comment by caternuson** [comment]
@BlitzCityDIY Yah, what @ladyada said.

It's weird that the CI failure seems to have changed. For the `c1e9533` commit, ESP32 was complaining about some polymorphism stuff:
```
   /home/runner/Arduino/libraries/Adafruit_SensorLab/Adafruit_SensorLab.cpp:378:10: error: deleting object of polymorphic class type 'Adafruit_HTS221' which has non-virtual destructor might cause undefined behavior [-Werror=delete-non-virtual-dtor]
     delete _hts221;
            ^~~~~~~
```
(which was also a bit of a head scratcher)

But for the `c60a8ff`, it's not just the ESP32 run, and the error is a simple missing library thing:
```
   /home/runner/Arduino/libraries/Adafruit_SensorLab/Adafruit_SensorLab.h:38:10: fatal error: Adafruit_MMC56x3.h: No such file or directory
   #include <Adafruit_MMC56x3.h>
            ^~~~~~~~~~~~~~~~~~~~
```
(so add to lib.prop like ladyada says)

**Comment by caternuson** [comment]
OK, now we're back to the ESP32 polymorph thing with the `462f7a9` commit :(
```
   /home/runner/Arduino/libraries/Adafruit_SensorLab/Adafruit_SensorLab.cpp:378:10: error: deleting object of polymorphic class type 'Adafruit_HTS221' which has non-virtual destructor might cause undefined behavior [-Werror=delete-non-virtual-dtor]
     delete _hts221;
            ^~~~~~~
```

**Comment by caternuson** [comment]
@ladyada @BlitzCityDIY I'm still at the same general point of questioning things as in comment above:
https://github.com/adafruit/Adafruit_SensorLab/pull/21#issuecomment-1185850723

**Comment by ladyada** [comment]
@caternuson i updated the lps2x, ht221 and mpu6050...and a few other libraries to 'fix' the warn-errors

@evaherrada please bump the arduino libraries first thing.... then @caternuson  you can wait till libmanager updates 4 hours later and rerun this!

**Pull request merged**
