### PR TITLE
adding HTS221 & demo

### PR DESCRIPTION
**Pull request by siddacious**
I added a humidity+temp demo because I didn't see any that use a humidity sensor.
Let me know if you don't want the hts221 to provide a temp sensor

### CODE REVIEW

**Comment by siddacious** [comment]
this is also going to fail until it's in the lib manager

**Comment by siddacious** [comment]
waiting on https://github.com/arduino/Arduino/issues/9796

**Comment by ladyada** [comment]
please kick if in the library manager

**Comment by ladyada** [comment]
@siddacious ok needs a little tweaking to merge cleanly!

**Review by ladyada — APPROVED** [review]
nice!

**Pull request merged**
